# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.SteamTab = QtWidgets.QWidget()
        self.SteamTab.setObjectName("SteamTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SteamTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(self.SteamTab)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.foldersButton = QtWidgets.QPushButton(self.SteamTab)
        self.foldersButton.setObjectName("foldersButton")
        self.verticalLayout_2.addWidget(self.foldersButton)
        self.wineButton = QtWidgets.QPushButton(self.SteamTab)
        self.wineButton.setObjectName("wineButton")
        self.verticalLayout_2.addWidget(self.wineButton)
        self.scanButton = QtWidgets.QPushButton(self.SteamTab)
        self.scanButton.setObjectName("scanButton")
        self.verticalLayout_2.addWidget(self.scanButton)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.SteamTab, "")
        self.LutrisTab = QtWidgets.QWidget()
        self.LutrisTab.setObjectName("LutrisTab")
        self.tabWidget.addTab(self.LutrisTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WGPM: A gaming prefix manager"))
        self.foldersButton.setText(_translate("MainWindow", "Add steam folders"))
        self.wineButton.setText(_translate("MainWindow", "Open wine"))
        self.scanButton.setText(_translate("MainWindow", "Scan games"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SteamTab), _translate("MainWindow", "Steam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LutrisTab), _translate("MainWindow", "Lutris"))
